### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-objectstore-hdfs#1]
Do you think its worth including instructions how the necessary installations / testing can be done with Docker?  I think that would facilitate testing.

**Comment by yahoNanJing** [comment]
Thanks @matthewmturner for your suggestion. I'll create a dockerfile for this later.

**Comment by yahoNanJing** [comment]
Hi @matthewmturner, the Dockerfile is created https://github.com/datafusion-contrib/datafusion-objectstore-hdfs/commit/492115205fcf6a264713aaedd271d06ec0410d21

**Comment by matthewmturner** [comment]
great i will test it out
