### ISSUE TITLE
Plans for publishing to crates.io

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-objectstore-hdfs#2]
Are there plans for publishing to crates.io?

**Comment by yahoNanJing** [comment]
Hi @matthewmturner, after https://github.com/apache/arrow-datafusion/pull/2065 merged to the master branch, I'll create 0.1.0 version and publish it to crates.io.

**Comment by yahoNanJing** [comment]
It seems it's not possible to publish it to crates.io, since the version of the datafusion dependencies is not specified. Maybe it's time to set a minor version for the datafusion now, like 7.0.1.

**Comment by yahoNanJing** [comment]
There's already 0.1.0 version published.
