### ISSUE TITLE
Implement based on the new object store abstraction 

### ISSUE THREAD

**Issue by yahoNanJing** [datafusion-contrib/datafusion-objectstore-hdfs#5]
https://github.com/apache/arrow-datafusion/issues/2489

**Comment by alamb** [comment]
@yahoNanJing  I may have some time to help with this project now that the object store has been incorporated into arrow https://github.com/apache/arrow-rs/issues/2030

My ulterior motive is that I would like to highlight the ability to plug in different implementations in the blog post I am writing about `object_store` and would like to use HDFS support in this crate as an example

Is anyone else planning to work on this ticket ?

**Comment by hrh007** [comment]
Is there any progress in the work, I am very interested in this work, I hope arrow-datafusion can use hdfs storage

**Comment by hrh007** [comment]
Is there any progress in this work, I am very interested in this work, and I hope arrow-datafusion can use hdfs storage

**Comment by hrh007** [comment]
Is there any progress in this work, I am very interested in this work, and I hope arrow-datafusion can use hdfs storage @alamb @yahoNanJing

**Comment by alamb** [comment]
I have not made any progress @hrh007  but `object_store` 0.4.0 has been released https://crates.io/crates/object_store/0.4.0

I would be happy to help if you wanted to start the work

**Comment by hrh007** [comment]
@alamb Thanks for reply, but object store 0.4.0 donot support HDFS either🤣

**Comment by alamb** [comment]
> @alamb Thanks for reply, but object store 0.4.0 donot support HDFS either🤣

Indeed -- but I think the interface changed a little so now that it is released it would be a good time to update the hdfs client

**Comment by alamb** [comment]
@dmetasoul01 mentioned on https://github.com/apache/arrow-datafusion/issues/3177#issuecomment-1220218640 that there is an implementation in blaze-rs

https://github.com/blaze-init/blaze/blob/master/native-engine/datafusion-ext/src/hdfs_object_store.rs

**Comment by yahoNanJing** [comment]
@hrh007, since hdfs object store depends on java environment, currently I don't put it into the object store crate.

And now the hdfs object store has already implemented the new interface of the object store and it's already been used by the Ballista. If you want the datafusion to use hdfs, you can refer to the Ballista for the usage.
